### ISSUE TITLE
Can't run default example

### ISSUE THREAD

**Issue by johnsoncze** [gameeapp/gamee-contest-2017#1]
Hi There,

I don't know what I'm doing wrong but if I follow your readme I get `sh: start: command not found` error after `npm run dev`

Node 4.2.6
npm 3.8.3

**Comment by johnsoncze** [comment]
I changed `package.json` to `"dev": "npm run server` and it's working but I'm not sure that this is right :)

**Comment by EntityB** [comment]
Your version is quite old. Can you try new versions? 

```
# node --version
v6.10.1

# npm --version
5.0.4
```

**Comment by johnsoncze** [comment]
Thank you for help. But I switched to versions you mentioned and it didn't help :(
Can you please explain me what is command `start` in package.json `"dev": "start npm run watch && start npm run server"`?

**Comment by EntityB** [comment]
Oh Im so sorry, I know where is the problem.  This command is OS dependent. So it doesnt run on your OS. 

`"dev": "start npm run watch && start npm run server"`

Just open 2 terminal and write:
```
npm run watch
npm run server
```

`npm run watch` is for webpack and does realtime building your `src` folder
`npm run server` creates server localhost:3000 with `www` folder, `build` folder and `dist` folder

**Comment by johnsoncze** [comment]
Thanks, you right I'm using OS X. I changed `"dev": "start npm run watch && start npm run server"` to `"dev": "npm run watch & npm run server"` and it works.
